spring:
  application:
    name: xxxxx-01
  data:
    mongodb:
      uri: mongodb://xxxx_admin:xxx@10.10.0.70:27017/xxxxs
      auto-index-creation: true
  cloud:
    service-registry:
      enabled: true
    consul:
      host: docker.dev.clemon
      port: 8500
      discovery:
        heartbeat:
          enabled: true
#          use-actuator-health: false
server:
  port: 8081

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-details: always